In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sharif-ml-1401-c6/assignment6-training-data.csv.csv
/kaggle/input/sharif-ml-1401-c6/assignment6-test-data-sample_submission.csv.csv
/kaggle/input/sharif-ml-1401-c6/assignment6-test-data.csv.csv

In [2]:
train=pd.read_csv('/kaggle/input/sharif-ml-1401-c6/assignment6-training-data.csv.csv')
test=pd.read_csv('/kaggle/input/sharif-ml-1401-c6/assignment6-test-data.csv.csv')
sub=pd.read_csv('/kaggle/input/sharif-ml-1401-c6/assignment6-test-data-sample_submission.csv.csv')

In [3]:
train

,PhraseId,SentenceId,Phrase,Sentiment
0,1,1,A series of escapades demonstrating the adage ...,1
1,2,1,A series of escapades demonstrating the adage ...,2
2,3,1,A series,2
3,4,1,A,2
4,5,1,series,2
...,...,...,...,...
155043,155044,8485,Santa Clause 2 ' is wondrously creative .,4
155044,155045,8485,' is wondrously creative .,2
155045,155046,8485,is wondrously creative .,3
155046,155047,8485,is wondrously creative,4
155047,155048,8485,wondrously creative,4

In [4]:
test

,PhraseId,SentenceId,Phrase,Sentiment,ID
0,155049,8486,"Girlfriends are bad , wives are worse and babi...",1,1
1,155050,8486,"Girlfriends are bad , wives are worse and babi...",0,2
2,155051,8486,"Girlfriends are bad , wives are worse and",2,3
3,155052,8486,"Girlfriends are bad , wives are worse",1,4
4,155053,8486,"Girlfriends are bad ,",2,5
...,...,...,...,...,...
1007,156056,8544,Hearst 's,2,1008
1008,156057,8544,forced avuncular chortles,1,1009
1009,156058,8544,avuncular chortles,3,1010
1010,156059,8544,avuncular,2,1011
1011,156060,8544,chortles,2,1012

In [5]:
sub

      Sentiment    ID
0             2     1
1             0     2
2             1     3
3             2     4
4             3     5
...         ...   ...
1007          1  1008
1008          0  1009
1009          2  1010
1010          4  1011
1011          4  1012

[1012 rows x 2 columns]

In [6]:
train=train.drop(['PhraseId','SentenceId'],axis=1)
test=test.drop(['PhraseId','SentenceId','ID'],axis=1)

In [7]:
train

                                                   Phrase  Sentiment
0       A series of escapades demonstrating the adage ...          1
1       A series of escapades demonstrating the adage ...          2
2                                                A series          2
3                                                       A          2
4                                                  series          2
...                                                   ...        ...
155043          Santa Clause 2 ' is wondrously creative .          4
155044                         ' is wondrously creative .          2
155045                           is wondrously creative .          3
155046                             is wondrously creative          4
155047                                wondrously creative          4

[155048 rows x 2 columns]

In [8]:
test

                                                 Phrase  Sentiment
0     Girlfriends are bad , wives are worse and babi...          1
1     Girlfriends are bad , wives are worse and babi...          0
2             Girlfriends are bad , wives are worse and          2
3                 Girlfriends are bad , wives are worse          1
4                                 Girlfriends are bad ,          2
...                                                 ...        ...
1007                                          Hearst 's          2
1008                          forced avuncular chortles          1
1009                                 avuncular chortles          3
1010                                          avuncular          2
1011                                           chortles          2

[1012 rows x 2 columns]

In [9]:
X=train['Phrase']
y=train['Sentiment']
test=test['Phrase']

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

X=v.fit_transform(X)
test=v.transform(test)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
X.shape

(155048, 15182)

In [12]:
test.shape

(1012, 15182)

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score


# Define and evaluate individual models
# model_lr = LogisticRegression()
# model_lr.fit(X_train, y_train)
# predictions_lr = model_lr.predict(X_test)
# accuracy_lr = accuracy_score(y_test, predictions_lr)

# model_nb = MultinomialNB()
# model_nb.fit(X_train, y_train)
# predictions_nb = model_nb.predict(X_test)
# accuracy_nb = accuracy_score(y_test, predictions_nb)

# model_svc = SVC()
# model_svc.fit(X_train, y_train)
# predictions_svc = model_svc.predict(X_test)
# accuracy_svc = accuracy_score(y_test, predictions_svc)

# model_rf = RandomForestClassifier()
# model_rf.fit(X_train, y_train)
# predictions_rf = model_rf.predict(X_test)
# accuracy_rf = accuracy_score(y_test, predictions_rf)

# model_knn = KNeighborsClassifier()
# model_knn.fit(X_train, y_train)
# predictions_knn = model_knn.predict(X_test)
# accuracy_knn = accuracy_score(y_test, predictions_knn)

model_dt = DecisionTreeClassifier()
model_dt.fit(X_train, y_train)
predictions_dt = model_dt.predict(X_test)
accuracy_dt = accuracy_score(y_test, predictions_dt)

# model_ada = AdaBoostClassifier()
# model_ada.fit(X_train, y_train)
# predictions_ada = model_ada.predict(X_test)
# accuracy_ada = accuracy_score(y_test, predictions_ada)

# model_mlp = MLPClassifier()
# model_mlp.fit(X_train, y_train)
# predictions_mlp = model_mlp.predict(X_test)
# accuracy_mlp = accuracy_score(y_test, predictions_mlp)

# # Print the results
# print("Model\t\t\tAccuracy")
# print("-" * 40)
# print(f"Logistic Regression\t{accuracy_lr:.4f}")
# print(f"Multinomial Naive Bayes\t{accuracy_nb:.4f}")
# print(f"Support Vector Machine\t{accuracy_svc:.4f}")
# print(f"Random Forest\t\t{accuracy_rf:.4f}")
# print(f"K-Nearest Neighbors\t{accuracy_knn:.4f}")
print(f"Decision Tree\t\t{accuracy_dt:.4f}")
# print(f"AdaBoost\t\t{accuracy_ada:.4f}")
# print(f"MLP Classifier\t\t{accuracy_mlp:.4f}")

Decision Tree		0.5936

In [15]:
y_pred=model_dt.predict(test)

In [16]:
test

<1012x15182 sparse matrix of type '<class 'numpy.int64'>'
	with 6250 stored elements in Compressed Sparse Row format>

In [17]:
df=pd.read_csv('/kaggle/input/sharif-ml-1401-c6/assignment6-test-data.csv.csv')
df=df.drop('Sentiment',axis=1)
df['Sentiment']=y_pred
od=df[['Sentiment','ID']]

In [18]:
od

      Sentiment    ID
0             2     1
1             2     2
2             1     3
3             0     4
4             0     5
...         ...   ...
1007          2  1008
1008          1  1009
1009          2  1010
1010          2  1011
1011          2  1012

[1012 rows x 2 columns]

In [19]:
od.to_csv('submission_sentiment_pred.csv',index=False)